require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/*'
    - '*.gemspec'
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/lite/ruby/boolean_spec.rb'
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
