require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/LineLength:
  Max: 100
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/**/*'
    - '*.gemspec'
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/lite/ruby/boolean_spec.rb'
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/SlicingWithRange:
  Enabled: false
