# frozen_string_literal: true

require 'date'

class Date
  include Lite::Ruby::DateHelper

  KEY_UNITS ||= {
    month: '%m',
    month_padded: '%m',
    month_unpadded: '%-m',
    month_blank: '%_m',
    month_name: '%B',
    month_name_abbr: '%b',
    month_year: '%m %Y',
    month_padded_year: '%m %Y',
    month_unpadded_year: '%-m %Y',
    month_blank_year: '%_m %Y',
    month_name_year: '%B %Y',
    month_name_abbr_year: '%b %Y',
    weekday: '%d',
    weekday_padded: '%d',
    weekday_unpadded: '%-d',
    weekday_blank: '%_d',
    weekday_name: '%A',
    weekday_name_abbr: '%a',
    sunday_week: '%U',
    monday_week: '%W',
    week_iso: '%V',
    week_year_iso: '%V-%G',
    date: '%B %-d, %Y',
    date_abbr: '%b %-d, %Y',
    date_iso: '%Y-%m-%d',
    day: '%B %-d',
    day_abbr: '%b %-d',
    day_iso: '%m-%d',
    yr: '%y',
    year_abbr: '%y',
    year: '%Y',
    year_day: '%Y-%m-%d',
    year_month: '%Y-%m',
    year_week: '%G-%V'
  }.freeze

  STRING_UNITS ||= {
    m: 'm',
    month: 'm',
    month_padded: 'm',
    mm: '-m',
    Month: '-m',
    month_unpadded: '-m',
    mmm: '_m',
    MONTH: '_m',
    month_blank: '_m',
    mmmm: 'B',
    month_name: 'B',
    mmmmm: 'b',
    month_name_abbr: 'b',
    swe: 'U',
    sunday_week: 'U',
    mwe: 'W',
    monday_week: 'W',
    we: 'V',
    week: 'V',
    w: 'u',
    weekday: 'u',
    ww: 'w',
    weekday_offset: 'w',
    www: 'A',
    weekday_name: 'A',
    wwww: 'a',
    weekday_name_abbr: 'a',
    d: 'd',
    day: 'd',
    day_padded: 'd',
    dd: '-d',
    Day: '-d',
    day_unpadded: '-d',
    ddd: '_d',
    DAY: '_d',
    day_blank: '_d',
    dddd: 'j',
    day_of_the_year: 'j',
    yy: 'y',
    yr: 'y',
    yyyy: 'Y',
    year: 'Y'
  }.freeze

end
